apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  selector:
    app: influxdb-deployment
  ports:
  - name: influxdb
    port: 8086
    targetPort: 8086
    protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 750Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
  claimRef:
      namespace: default
      name: influxdb-pv-claim
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb-deployment
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
