apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb-deployment
    spec:
      restartPolicy: Always
      containers:
      - name: influxdb-deployment
        image: influx
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: "/var/lib/influxdb"
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
