apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ft_services
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: ft_services
    tier: mysql
  clusterIP: None
  externalName: mysql.default

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mysqlingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: mysql.info
  - http:
      paths:
      - path: /
        backend:
          serviceName: mysql
          servicePort: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: ft_services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
