apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql-deployment
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql-deployment
    type: ClusterIP

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 750Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
  claimRef:
      namespace: default
      name: mysql-pv-claim
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-deployment
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
