apiVersion: v1
kind: Service
metadata:
    name: grafana-svc
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana-deployment

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: default
  labels:
    app: grafana-deployment
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 450Mi

