apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: grafana-deployment
  template:
    metadata:
      labels:
        app: grafana-deployment
    spec:
      restartPolicy: Always
      containers:
      - name: grafana-deployment
        image: grafan
        imagePullPolicy: Never
         env:
          - name: INFLUXDB_CA_VA_LA
        volumeMounts:
          - name: grafana-pv
            mountPath: /root/grafana/data
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
      volumes:
      - name: grafana-pv
        persistentVolumeClaim:
            claimName: grafana-pvc
