apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: grafana-deployment
  template:
    metadata:
      labels:
        app: grafana-deployment
    spec:
      restartPolicy: Always
      containers:
      - name: grafana-deployment
        image: grafana
        imagePullPolicy: Never
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
