apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: Nate
  annotation:
	kubernetes.io/ingress.class: nginx
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 22
    name: ssh
  selector:
    app: ft_services
    tier: nginx
  type: LoadBalancer
