apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  type: NodePort
  ports:
  - port: 32080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 32443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 32022
    nodePort: 22
    targetPort: 22
    protocol: TCP
    name: ssh
  selector:
    app: nginx
  externalName: ng.inx
