version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
  database:
    image: mysql:5.7
    container_name: phpmyadmin
    volumes:
      - mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/1-dump.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: data
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

volumes:
  mysql:
