apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-deployment
      tier: admin
  template:
    metadata:
      labels:
        app: phpmyadmin-deployment
        tier: admin
    spec:
      restartPolicy: Always
      containers:
      - name: phpmyadmin-deployment
        image: phpadm
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
