apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      restartPolicy: Always
      containers:
      - image: wordpr
        imagePullPolicy: Never
        name: wordpress
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: wp-pv-volume
          mountPath: /var/www/html
      volumes:
      - name: wp-pv-volume
        persistentVolumeClaim:
          claimName: wp-pv-claim
