apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress-deployment
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-volume
  labels:
    type: local
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 550Mi
  hostPath: 
    path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 550Mi
