apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 5050
  selector:
    app: ft_services
    tier: frontend
  type: NodePort

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-volume
  labels:
    type: local
    app: ft_services
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 700Mi
  hostPath: 
    path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: ft_services
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi
