apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        tier: frontend
    spec:
      restartPolicy: Always
      containers:
      - image: wordpress:4.8-apache
       # imagePullPolicy: Never
        name: wordpress
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
