apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  type: ClusterIP
  ports:
  - name: telegraf
    port: 8125
    protocol: TCP
    targetPort: 8125
  selector:
    app: telegraf
  externalName: tele.graf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-account
  labels:
    app: telegraf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf-account
  namespace: default
