apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  selector:
    app: ftps-deployment
  type: LoadBalancer
  ports:
    - name: pftps-20
      port: 20
      targetPort: 20
    - name: pftps-21
      port: 21
      targetPort: 21
