apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: NodePort
  ports:
  - port: 20
    nodePort: 20
    protocol: TCP
    name: ftp
  - port: 21
    nodePort: 21
    protocol: TCP
    name: ftps
  - port: 21000
    nodePort: 21000
    protocol: TCP
    name: ftps-pasv1
  selector:
    app: ftps
  externalName: ft.services.ftps
