apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  selector:
    app: grafana-deployment
  type: LoadBalancer
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: default
  labels:
    app: grafana-deployment
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
