apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps-deployment
  template:
    metadata:
      labels:
        app: ftps-deployment
    spec:
      containers:
      - name: ftps-deployment
        image: ftps_server
        volumeMounts:
          - name: ftps-pv
            mountPath: /ftp
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
      volumes:
      - name: ftps-pv
