apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps-deployment
  template:
    metadata:
      labels:
        app: ftps-deployment
    spec:
      containers:
      - name: ftps-deployment
        image: ftps_server
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /utils/status.sh
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        - containerPort: 21005
