apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      volumes:
      - name: configmap-volume
        configMap:
          name: telegraph
      containers:
        - name: telegraf
          image: telegraf:1.12-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: HOSTNAME
              value: "cluster-status"
          volumeMounts:
          - mountPath: /etc/telegraf
            name: configmap-volume
